var _gsTimer=null,_GS_MAX=40,_gsBrandClass={FLN:"fln",KW:"kw",INT:"int"};
function globalSearchInput(q){var c=document.getElementById("gs-clear"),i=document.getElementById("gs-icon");if(c)c.style.display=q.length>0?"block":"none";if(i)i.style.display=q.length>0?"none":"block";clearTimeout(_gsTimer);if(!q||q.trim().length<2){_gsClosePanelOnly();return;}_gsTimer=setTimeout(function(){_gsRender(q.trim());},180);}
function _gsClosePanelOnly(){var p=document.getElementById("global-results-panel"),o=document.getElementById("gs-overlay");if(p)p.classList.remove("open");if(o)o.classList.remove("open");}
function _gsEsc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function _gsRender(q){var panel=document.getElementById("global-results-panel"),overlay=document.getElementById("gs-overlay");if(!panel)return;var qu=q.toUpperCase(),cat=window.CATALOG_DATA||[],seen={},byCode=[],byDesc=[],i,p;for(i=0;i<cat.length;i++){p=cat[i];if(seen[p.c])continue;if(p.c&&String(p.c).toUpperCase().indexOf(qu)>=0){seen[p.c]=1;byCode.push(p);if(byCode.length>=10)break;}}for(i=0;i<cat.length&&byDesc.length<_GS_MAX-byCode.length;i++){p=cat[i];if(seen[p.c])continue;if((p.d||"").toUpperCase().indexOf(qu)>=0){seen[p.c]=1;byDesc.push(p);}}var total=byCode.length+byDesc.length;if(total===0){panel.innerHTML="<div class=\"grp-header\"><span class=\"grp-count\">0 resultados</span></div><div class=\"grp-empty\">Sin resultados</div>";panel.classList.add("open");if(overlay)overlay.classList.add("open");return;}function ri(p){var ci=(typeof CAT_ICONS!=="undefined"&&CAT_ICONS[p.k])||"*",bc=_gsBrandClass[p.b]||"fln";var imgH=p.i?"<img src=\""+_gsEsc(p.i)+"\" loading=\"lazy\">":" <span class=\"grp-img-ph\">"+ci+"</span>";return "<div class=\"grp-item\" onclick=\"gsSelectPieza("+JSON.stringify(p.m||"")+","+JSON.stringify(String(p.c||""))+")\">"+"<div class=\"grp-img\">"+imgH+"</div>"+"<div class=\"grp-info\"><div class=\"grp-code "+bc+"\"><b>#"+_gsEsc(String(p.c||""))+"</b></div><div class=\"grp-desc\">"+_gsEsc(p.d||"")+"</div></div>"+"<div class=\"grp-meta\"><span class=\"grp-cat\">"+ci+" "+_gsEsc(p.k||"")+"</span><span class=\"grp-model\">"+_gsEsc(p.m||"")+"</span></div></div>";}var html="<div class=\"grp-header\"><span class=\"grp-count\">"+total+" resultado"+(total!==1?"s":"")+" de "+cat.length.toLocaleString("es-MX")+"</span><span class=\"grp-hint\">clic al modelo</span></div><div class=\"grp-list\">";if(byCode.length>0){html+="<div class=\"grp-section-label\">por codigo</div>";for(i=0;i<byCode.length;i++)html+=ri(byCode[i]);}if(byDesc.length>0){html+="<div class=\"grp-section-label\">por descripcion</div>";for(i=0;i<byDesc.length;i++)html+=ri(byDesc[i]);}html+="</div>";panel.innerHTML=html;panel.classList.add("open");if(overlay)overlay.classList.add("open");}
function gsSelectPieza(modelId,codigo){globalSearchClear();if(!modelId)return;var allMods=[].concat(DATA.FRT.modelos,DATA.KW.modelos,DATA.INT.modelos),mod=null,i;for(i=0;i<allMods.length;i++){if(allMods[i].id===modelId){mod=allMods[i];break;}}if(!mod)return;var bk=DATA.FRT.modelos.some(function(m){return m.id===modelId;})?"FRT":DATA.KW.modelos.some(function(m){return m.id===modelId;})?"KW":"INT";var allBtns=Array.from(document.querySelectorAll(".marca-btn"));var bb=allBtns.filter(function(b){return (b.getAttribute("onclick")||"").indexOf(bk)>=0;})[0];if(bb)bb.click();setTimeout(function(){var card=document.querySelector(".mod-card[data-id=\""+modelId+"\"]");if(card){card.click();card.scrollIntoView({behavior:"smooth",block:"center"});}else if(typeof selMod==="function")selMod(mod);setTimeout(function(){var ci=document.getElementById("cat-search");if(ci){ci.value=String(codigo);if(typeof catSearch==="function")catSearch(String(codigo));}var cs=document.querySelector(".cat-section");if(cs)cs.scrollIntoView({behavior:"smooth",block:"start"});},550);},150);}
function globalSearchFocus(){var input=document.getElementById("global-search-input"),q=input&&input.value?input.value.trim():"";if(q.length>=2)_gsRender(q);}
function globalSearchClear(){var i=document.getElementById("global-search-input"),p=document.getElementById("global-results-panel");var o=document.getElementById("gs-overlay"),c=document.getElementById("gs-clear"),ic=document.getElementById("gs-icon");if(i)i.value="";if(p)p.classList.remove("open");if(o)o.classList.remove("open");if(c)c.style.display="none";if(ic)ic.style.display="block";}
document.addEventListener("keydown",function(e){if(e.key==="Escape")globalSearchClear();if((e.ctrlKey||e.metaKey)&&e.key==="k"){e.preventDefault();var el=document.getElementById("global-search-input");if(el)el.focus();}});
function openTruckZoom(src){
  var ov=document.getElementById('truck-zoom-overlay');
  var img=document.getElementById('truck-zoom-img');
  if(!ov||!img||!src)return;
  img.src=src;
  ov.classList.add('open');
  document.body.style.overflow='hidden';
}
function closeTruckZoom(){
  var ov=document.getElementById('truck-zoom-overlay');
  if(ov)ov.classList.remove('open');
  document.body.style.overflow='';
}
